### ISSUE TITLE
Cannot start JFXtras Ensemble via WebStart from website/jnlp file

### ISSUE THREAD

**Issue by mathiaslin** [JFXtras/jfxtras.github.com#1]
When trying to start JFXtras Ensemble from the website via webstart / jnlp, I'm getting the following error from webstart:

System info:
Mac OS X Lion 10.7.4

java version "1.7.0_05"
Java(TM) SE Runtime Environment (build 1.7.0_05-b05)
Java HotSpot(TM) 64-Bit Server VM (build 23.1-b03, mixed mode)

Exception:
com.sun.deploy.net.FailedDownloadException: Unable to load resource: file:/Users/myuser/Downloads/Ensemble.jar
	at com.sun.deploy.net.DownloadEngine.actionDownload(DownloadEngine.java:1416)
	at com.sun.deploy.net.DownloadEngine.getCacheEntry(DownloadEngine.java:1569)
	at com.sun.deploy.net.DownloadEngine.getCacheEntry(DownloadEngine.java:1547)
	at com.sun.deploy.net.DownloadEngine.getResourceCacheEntry(DownloadEngine.java:1654)
	at com.sun.deploy.net.DownloadEngine.getResourceCacheEntry(DownloadEngine.java:1578)
	at com.sun.deploy.net.DownloadEngine.getResource(DownloadEngine.java:215)
	at com.sun.javaws.LaunchDownload$DownloadTask.call(LaunchDownload.java:1983)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)

Wrapped Exception:

java.io.FileNotFoundException: /Users/myuser/Downloads/Ensemble.jar (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:120)
	at java.io.FileInputStream.<init>(FileInputStream.java:79)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:70)
	at com.sun.deploy.net.BasicHttpRequest.doRequest(BasicHttpRequest.java:179)
	at com.sun.deploy.net.BasicHttpRequest.doRequest(BasicHttpRequest.java:112)
	at com.sun.deploy.net.BasicHttpRequest.doGetRequest(BasicHttpRequest.java:77)
	at com.sun.deploy.net.DownloadEngine.actionDownload(DownloadEngine.java:1226)
	at com.sun.deploy.net.DownloadEngine.getCacheEntry(DownloadEngine.java:1569)
	at com.sun.deploy.net.DownloadEngine.getCacheEntry(DownloadEngine.java:1547)
	at com.sun.deploy.net.DownloadEngine.getResourceCacheEntry(DownloadEngine.java:1654)
	at com.sun.deploy.net.DownloadEngine.getResourceCacheEntry(DownloadEngine.java:1578)
	at com.sun.deploy.net.DownloadEngine.getResource(DownloadEngine.java:215)
	at com.sun.javaws.LaunchDownload$DownloadTask.call(LaunchDownload.java:1983)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)

**Comment by tbee** [comment]
Ensemble has been replaced with JFXtrasSamples in 2013.
