### ISSUE TITLE
Cannot start fxtras-labs-samples-8.0-r4-SNAPSHOT- with Java 1.8.0_45

### ISSUE THREAD

**Issue by TheMSB** [JFXtras/jfxtras.github.com#5]
Since updating to Java 1.8.0_45 the application will no longer run.

File: fxtras-labs-samples-8.0-r4-SNAPSHOT-
Java version: 1.8.0_45

Error Parse:

Initialising FXSampler sample scanner...
	Discovering projects...
		Found project 'JFxtras', with sample base package 'jfxtras.samples'
		Found project 'JFxtrasLabs', with sample base package 'jfxtras.labs.samples'
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$152(LauncherImpl.java:182)
	at com.sun.javafx.application.LauncherImpl$$Lambda$51/1793329556.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.time.DateTimeException: Invalid date 'APRIL 31'
	at java.time.LocalDate.create(LocalDate.java:431)
	at java.time.LocalDate.of(LocalDate.java:269)
	at jfxtras.samples.controls.agenda.AgendaSample1.<init>(AgendaSample1.java:189)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at fxsampler.util.SampleScanner.discoverSamples(SampleScanner.java:86)
	at fxsampler.FXSampler.start(FXSampler.java:103)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$159(LauncherImpl.java:863)
	at com.sun.javafx.application.LauncherImpl$$Lambda$54/1988525694.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$172(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl$$Lambda$47/553264065.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
	at com.sun.javafx.application.PlatformImpl$$Lambda$49/1211714189.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
	at com.sun.javafx.application.PlatformImpl$$Lambda$48/1789447862.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Exception running application fxsampler.FXSampler

**Comment by tbee** [comment]
Ah, the code reads: withEndLocalDateTime(LocalDate.of(lTodayYear, lTodayMonth, lTodayDay + 1).atStartOfDay()) 

See the "+ 1"? That will result in april 31st, which does not exist. Java calendar and date automatically wraps around to the next month in that situation. So tomorrow it will run and I will fix the bug.

Thanks for reporting

**Comment by tbee** [comment]
fixed
